### ISSUE TITLE
Addition

### ISSUE THREAD

**Issue by dahead** [PySimpleGUI/YTDownloader#3]
https://github.com/PySimpleGUI/YTDownloader/blob/244684a7c46b1ca983dd1462deb0e341cf780cd8/main.py#L45

This should probably be number1 + number2.

**Comment by PySimpleGUI** [comment]
Thank you!

I dunno why I missed this issue.  I had completely forgotten about this project until I today when I was reminded that I did something with pytube, but didn't remember exactly what until X1 found this project when I scoured my hard drive.

Thank you for taking a moment to report the problem.  I checked in the fix.
